fos_rest:
    routing_loader:
        default_format: json
        include_format: false

    format_listener:
        rules:
            - { priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: true
