api_login_check:
    path: /api/auth/login

registration:
    resource: App\Controller\Api\RegistrationController
    type: rest
    prefix: /api/auth

post:
    resource: App\Controller\Api\PostController
    type: rest
    prefix: /api

comment:
    resource: App\Controller\Api\PostController
    type: rest
    prefix: /api
