parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    kernel.listener.doctrine:
        class: 'App\Listener\DoctrineListener'
        public: false
        tags:
            - { name: doctrine.event_listener, event: preFlush, method: preFlush }
